spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:mysql://192.168.189.128:3306/layim?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    password: root
  http:
        multipart:
          max-file-size: 30MB
          max-request-size: 30MB
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    open-in-view: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    check-template: true
    suffix: .html
    encoding: utf-8
    content-type: text/html
    mode: HTML5
#debug: true
server:
     port: 8887

layim.websocket:
    ip: 127.0.0.1
    port: 8888
    heartBeatTimeout: 0
layim.upload.dir: G:\JavaProject\SpringBootLayIM\upload

logging:
  level:
    jdbc:
      only: ERROR
      audit: ERROR
      sqltiming: ERROR
      resultset: ERROR
      connection: ERROR